/// <reference lib="dom" />
/// <reference lib="dom.iterable" />
/**
 * EPUB reader client — runs inside the Android WebView. Bundled by
 * esbuild into `assets/js/reader-bundle.js` and loaded via a
 * `<script src="file:///android_asset/js/reader-bundle.js">` tag from
 * the HTML generated by `components/reader/epub-html.ts`.
 *
 * Runtime inputs come from `window.__READR_CONFIG` (set by a tiny
 * inline script in the HTML before this bundle loads) and from
 * postMessage events sent by the RN host via `injectJavaScript` /
 * direct postMessage.
 */

// ─── Globals ──────────────────────────────────────────────────────────

declare global {
  interface Window {
    ReactNativeWebView?: { postMessage(data: string): void };
    __foliate?: {
      makeBook: (f: File) => Promise<FoliateBook>;
      Overlayer: FoliateOverlayer;
    };
    __READR_CONFIG?: { bookUrl: string };
  }
}

// Foliate-js has no public TS types; these are the shallow slices we
// rely on. `any` escape hatches are marked — they're where foliate's
// internal machinery is too gnarly to describe compactly.
interface FoliateTocItem {
  label: string;
  href: string;
  subitems?: FoliateTocItem[];
}
interface FoliateBook {
  sections: Array<{ id?: string; createDocument(): Promise<Document> }>;
  toc?: FoliateTocItem[];
  search?(q: string): AsyncIterable<{ cfi: string; excerpt: string; label: string }>;
}
interface FoliateOverlayer {
  highlight: unknown;
  underline: unknown;
  squiggly: unknown;
}
interface FoliateView extends HTMLElement {
  open(book: FoliateBook): Promise<void>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  goTo(target: any): Promise<unknown>;
  goToFraction(f: number): Promise<unknown>;
  prev(): Promise<unknown>;
  next(): Promise<unknown>;
  clearSearch?(): void;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  addAnnotation?(ann: any, remove?: boolean): void;
  getCFI?(index: number, range: Range): string;
  getSectionFractions?(): number[];
  renderer?: {
    page?: number;
    pages?: number;
    getContents?(): Array<{ doc: Document; index: number }>;
  };
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  lastLocation?: any;
}

interface Theme {
  bg?: string;
  fg?: string;
  fontSize?: number;
  lineHeight?: number;
  fontWeight?: number;
  fontFamily?: string;
  margin?: number;
  marginV?: number;
  tapToTurn?: boolean;
  pageTurnMode?: 'tap' | 'swipe' | 'both';
  isEink?: boolean;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type RNMessage = { type: string; payload?: any };

// ─── Module state ─────────────────────────────────────────────────────

let view: FoliateView | null = null;
let book: FoliateBook | null = null;
// Whether tap-on-left/right turns the page. Flipped from setTheme.
let tapToTurn = true;
// Whether swipe/drag gestures are allowed to turn pages. When false,
// capture-phase touch listeners on the paginator AND each iframe doc
// swallow touchmove so foliate's built-in swipe handler never fires.
let swipeEnabled = true;
// Most recently-loaded section document. Foliate loads each EPUB
// section into its own iframe; TTS and tap-handler installation
// operate on whatever's currently shown.
let currentSectionDoc: Document | null = null;

// Page counting — populated by a hidden-container scrollWidth scan
// on open / theme change, then refined by foliate's own paginator.
let sectionPageCounts: Record<number, number> = {};
let sectionPageCountsLocked = false;
let currentSectionIndex = 0;

// Theme CSS that gets injected into every new section document.
let currentThemeCSS = '';
let currentTheme: Theme = {};
// Latest CFI we've seen, mirrored from every relocate event the user
// triggered. Used to restore position across theme changes.
let currentCfi: string | null = null;
// Suppresses relocate-driven currentCfi updates while applyTheme is
// reflowing. The reflow fires intermediate relocate events with the
// wrong CFI (start of section, page 1, etc.) — if those leak into
// currentCfi the *next* theme change saves a corrupted value and
// "restores" you to page 1.
let suppressCfiUpdates = false;
// Generation counter for applyTheme. Each call bumps it; in-flight
// async work checks the generation and bails out if a newer theme
// change has started, so stale IIFEs can't show the viewer at the
// wrong time or overwrite state after the user moved on.
let themeGen = 0;
// Map of note CFI → noteType ('typed' | 'handwritten'). Foliate's
// show-annotation event drops custom annotation fields, so we mirror
// classifications here and consult it when routing a tap.
const noteCfis = new Map<string, 'typed' | 'handwritten'>();

// ─── postMessage helpers ─────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function post(type: string, payload: any): void {
  window.ReactNativeWebView?.postMessage(JSON.stringify({ type, payload }));
}

// ─── Incoming RN messages ─────────────────────────────────────────────

function handleRNMessage(data: RNMessage): void {
  if (!view) return;
  switch (data.type) {
    case 'setTheme':
      applyTheme(data.payload);
      break;
    case 'goToLocation':
      if (data.payload.cfi) view.goTo(data.payload.cfi);
      else if (data.payload.fraction != null) view.goToFraction(data.payload.fraction);
      break;
    case 'goToChapter':
      if (data.payload.href) {
        try {
          view.goTo(data.payload.href);
        } catch {
          // Some hrefs need to be resolved against the book's base
          try { view.goTo({ href: data.payload.href }); } catch { /* ignore */ }
        }
      }
      break;
    case 'prevPage':
      view.prev();
      break;
    case 'nextPage':
      view.next();
      break;
    case 'search':
      performSearch(data.payload.query);
      break;
    case 'clearSearch':
      if (view.clearSearch) view.clearSearch();
      break;
    case 'getPageText': {
      // Return the visible section's plain text for TTS. Fall back to
      // empty string if the section hasn't loaded yet.
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const text = (currentSectionDoc?.body as any)?.innerText?.trim() ?? '';
      post('pageText', { text });
      break;
    }
    case 'copyToClipboard': {
      const text: string = data.payload.text || '';
      if (text) copyTextToClipboard(text);
      break;
    }
    case 'addHighlight': {
      const cfi = data.payload.cfi || data.payload.cfiRange;
      if (!cfi) break;
      if (view.addAnnotation) {
        try {
          view.addAnnotation({ value: cfi, color: data.payload.color || 'yellow', kind: 'highlight' });
        } catch (err) {
          post('highlightError', { cfi, error: String(err) });
        }
      }
      break;
    }
    case 'removeHighlight': {
      const cfi = data.payload.cfi || data.payload.cfiRange;
      if (!cfi || !view.addAnnotation) break;
      try {
        // foliate: passing truthy 2nd arg removes the annotation
        view.addAnnotation({ value: cfi }, true);
      } catch { /* ignore */ }
      break;
    }
    case 'addNote': {
      // Notes share foliate's annotation machinery but render as a
      // squiggly/underline so they're distinguishable from highlights
      // and don't block the underlying text. The noteType controls
      // the visual style so typed notes and drawings look different.
      const cfi: string | undefined = data.payload.cfi;
      const noteType: 'typed' | 'handwritten' =
        data.payload.noteType === 'handwritten' ? 'handwritten' : 'typed';
      if (!cfi || !view.addAnnotation) break;
      try {
        view.addAnnotation({ value: cfi, kind: 'note', noteType });
        noteCfis.set(cfi, noteType);
      } catch (err) {
        post('noteError', { cfi, error: String(err) });
      }
      break;
    }
    case 'removeNote': {
      const cfi: string | undefined = data.payload.cfi;
      if (!cfi || !view.addAnnotation) break;
      try {
        view.addAnnotation({ value: cfi }, true);
        noteCfis.delete(cfi);
      } catch { /* ignore */ }
      break;
    }
  }
}

function copyTextToClipboard(text: string): void {
  const fallback = () => {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.style.position = 'fixed';
    ta.style.left = '-9999px';
    document.body.appendChild(ta);
    ta.select();
    document.execCommand('copy');
    document.body.removeChild(ta);
  };
  try {
    navigator.clipboard.writeText(text).catch(fallback);
  } catch {
    fallback();
  }
}

// ─── Theming ──────────────────────────────────────────────────────────

const BUNDLED_FONTS = [
  'Literata', 'Lora', 'Merriweather', 'EB Garamond', 'Source Serif 4',
  'Noto Serif', 'Crimson Text', 'Libre Baskerville', 'Playfair Display',
  'PT Serif', 'Roboto Slab', 'Roboto', 'Open Sans', 'Inter', 'Nunito',
  'Fira Mono', 'IBM Plex Mono',
];

function fontFaceCSS(): string {
  return BUNDLED_FONTS.map((f) => {
    const file = f.replace(/\s+/g, '');
    return `@font-face{font-family:'${f}';src:url('file:///android_asset/fonts/${file}.ttf')}`;
  }).join('\n');
}

function buildThemeCSS(theme: Theme): string {
  const eink = !!theme.isEink;
  const fg = theme.fg || '#111';
  const fs = theme.fontSize || 16;
  const lh = theme.lineHeight || 1.6;
  const fw = theme.fontWeight || 400;
  const ff = theme.fontFamily || '';
  const marginH = theme.margin ?? 48;
  const marginV = theme.marginV ?? 24;

  const base = [
    fontFaceCSS(),
    // Keep the iframe completely transparent so the host's theme bg
    // shows through — no inner/outer colour mismatch possible, even
    // while a mid-transition section is still carrying old styles.
    `html, body { background: transparent !important; }`,
    // Force ALL elements: color, transparent bg, typography, no borders.
    // Books embed their own stylesheets that add decorative borders in
    // hard-coded colours (sepia rules, beige dividers, etc) which stay
    // stale through theme changes. Kill them all — the theme's
    // typography should speak for itself.
    '* {',
    `  color: ${fg} !important;`,
    `  background: transparent !important;`,
    `  background-color: transparent !important;`,
    `  background-image: none !important;`,
    `  border: 0 !important;`,
    `  outline: 0 !important;`,
    `  box-shadow: none !important;`,
    `  line-height: ${lh} !important;`,
    `  font-weight: ${fw} !important;`,
    ff ? `  font-family: ${ff} !important;` : '',
    '}',
    // Tables still need their grid to be readable — restore a minimal
    // themed border for table cells only.
    `table, th, td { border: 1px solid ${fg} !important; border-collapse: collapse !important; }`,
    `html { font-size: ${fs}px !important; }`,
    // Keep all user-visible page margins inside the section document
    // itself. Foliate's `margin` attribute only controls the outer
    // paginator grid, and host padding is too indirect to be a reliable
    // page-margin control.
    `body { margin: 0 !important; padding: ${marginV}px ${marginH}px !important; box-sizing: border-box !important; }`,
    'img { max-width: 100% !important; height: auto !important; background-color: transparent !important; }',
    'a, a:link, a:visited { text-decoration: underline; }',
  ];

  if (eink) {
    // Kill everything a slow panel can't handle. Books embed their own
    // stylesheets that can add fades, glows, and color decorations; the
    // !important wildcards win over them.
    base.push(
      'img { filter: grayscale(100%) contrast(1.15); }',
      '* {',
      '  text-shadow: none !important;',
      '  animation: none !important;',
      '  transition: none !important;',
      '  filter: none !important;',
      '}',
      // Re-apply after wildcard reset.
      'img { filter: grayscale(100%) contrast(1.15) !important; }',
      `a, a:link, a:visited, a:hover { color: ${fg} !important; text-decoration: underline; }`,
    );
  }

  return base.join('\n');
}

function injectThemeIntoDoc(doc: Document | null): void {
  if (!doc || !currentThemeCSS) return;
  try {
    let style = doc.getElementById('readr-theme') as HTMLStyleElement | null;
    if (!style) {
      style = doc.createElement('style');
      style.id = 'readr-theme';
      (doc.head || doc.documentElement).appendChild(style);
    }
    style.textContent = currentThemeCSS;
  } catch { /* ignore */ }
}

// Push the current theme CSS into every section iframe foliate has
// mounted. Foliate keeps adjacent sections alive for fast page turns,
// so injecting only into `currentSectionDoc` leaves the others stuck
// on the previous theme — visible as a flash of the old background
// when you turn a page after a theme change.
function injectThemeIntoAllDocs(): void {
  try {
    const contents = view?.renderer?.getContents?.() ?? [];
    for (const c of contents) injectThemeIntoDoc(c.doc);
  } catch { /* ignore */ }
  // Also cover currentSectionDoc in case getContents is empty (fresh
  // load, renderer not ready yet).
  if (currentSectionDoc) injectThemeIntoDoc(currentSectionDoc);
}

// Serialized signature of layout-affecting theme fields. We compare
// this against the previous call's signature to decide whether a
// given applyTheme needs to trigger a reflow or not.
function layoutSignature(t: Theme): string {
  return JSON.stringify([
    t.margin ?? null,
    t.marginV ?? null,
    t.fontSize ?? null,
    t.fontFamily ?? null,
    t.fontWeight ?? null,
    t.lineHeight ?? null,
  ]);
}
let lastLayoutSig: string | null = null;

function applyTheme(theme: Theme): void {
  const prevTheme = currentTheme;
  currentTheme = theme;
  const sig = layoutSignature(theme);
  // First call (lastLayoutSig null) ALWAYS runs the full path so
  // margins/gap/etc get initially applied. Subsequent calls only
  // reflow when the signature changed; colour-only changes skip.
  const isFirst = lastLayoutSig == null;
  const layoutChanged = isFirst || sig !== lastLayoutSig;
  lastLayoutSig = sig;
  post('debug', { msg: `applyTheme isFirst=${isFirst} layoutChanged=${layoutChanged} prevBg=${prevTheme.bg} newBg=${theme.bg}` });

  // ── Colour work (always, cheap, no reflow) ───────────────────────
  const root = document.documentElement;
  root.style.setProperty('--bg', theme.bg || '#fff');
  root.style.setProperty('--fg', theme.fg || '#111');
  const bgColor = theme.bg || '#fff';
  root.style.cssText = `background:${bgColor}!important`;
  document.body.style.cssText = `background:${bgColor}!important;margin:0;padding:0`;
  const viewer = document.getElementById('viewer');
  if (viewer) viewer.style.cssText = `width:100%;height:100%;background:${bgColor}`;
  if (view) {
    view.style.background = bgColor;
    forceShadowBackground(view, bgColor);
  }

  // Page-turn mode (not layout-affecting)
  const mode: 'tap' | 'swipe' | 'both' =
    theme.pageTurnMode ?? (theme.tapToTurn === false ? 'swipe' : 'both');
  tapToTurn = mode !== 'swipe';
  swipeEnabled = mode !== 'tap';

  // Keep the section-iframe CSS string current so new sections pick
  // up the latest theme. Also push it into the current section doc —
  // foliate's column positions stay put through an in-iframe restyle,
  // so the visible page doesn't jump on a colour-only change.
  currentThemeCSS = buildThemeCSS(theme);
  if (currentSectionDoc) injectThemeIntoDoc(currentSectionDoc);

  if (!view) return;

  // ── Layout work (only when something layout-affecting changed) ───
  if (!layoutChanged) return;

  // Hide the viewer BEFORE any reflow-triggering setAttribute calls.
  // setAttribute on foliate-view fires attributeChangedCallback →
  // render() → paint synchronously; if the cover isn't up first, the
  // user sees a frame of "page 1" before it's hidden.
  //
  // On the very first applyTheme call the book is still loading so
  // the viewer is already empty — we only need to cover on subsequent
  // (user-triggered) layout changes.
  const needsRestore = !isFirst;
  const myGen = needsRestore ? ++themeGen : themeGen;
  const savedCfi = needsRestore ? currentCfi : null;
  const cover = document.getElementById('theme-transition-cover');
  if (needsRestore) {
    suppressCfiUpdates = true;
    if (cover) {
      cover.style.background = bgColor;
      cover.style.display = 'block';
    }
  }

  // Apply attributes/styles. setAttribute on foliate-view triggers
  // attributeChangedCallback → render() → reflow, which is what
  // moves us off the user's current page and forces the restore.
  // Foliate's paginator drops the attribute value straight into a CSS
  // variable (--_gap, --_max-inline-size, --_max-block-size) and uses
  // it inside calc()/minmax() as a length. CSS length values need a
  // unit (other than literal `0`), so bare `99999` silently resolves
  // to invalid and the cap falls back to foliate's 720px/1440px
  // default — that's why "0 isn't 0" and the horizontal margin slider
  // appears to do nothing on wide screens.
  view.setAttribute('gap', '0px');
  view.setAttribute('max-inline-size', '99999px');
  view.setAttribute('max-block-size', '99999px');
  // The visible page margins now come from the injected section CSS.
  // Keep foliate's own outer grid gutters disabled so the controls map
  // 1:1 to the text block.
  view.setAttribute('margin', '0px');
  view.style.paddingLeft = '0';
  view.style.paddingRight = '0';
  view.style.paddingTop = '0';
  view.style.paddingBottom = '0';

  if (!needsRestore) return;
  sectionPageCounts = {};
  sectionPageCountsLocked = false;
  (async () => {
    const stale = () => myGen !== themeGen;
    // Only the newest IIFE may touch the cover on the way out; stale
    // IIFEs would otherwise reveal the viewer mid-transition.
    const hideCover = () => {
      if (cover) cover.style.display = 'none';
    };
    try {
      try { await document.fonts?.ready; } catch { /* ignore */ }
      await new Promise((r) => setTimeout(r, 200));
      if (stale()) return;
      if (savedCfi && view?.goTo) {
        try {
          await view.goTo(savedCfi);
          post('debug', { msg: `restore gen=${myGen} goTo done` });
        } catch (err) {
          post('debug', { msg: `restore gen=${myGen} goTo THREW: ${(err as Error)?.message}` });
        }
      } else {
        post('debug', { msg: `restore gen=${myGen} SKIPPED savedCfi=${savedCfi}` });
      }
      if (stale()) return;
      // Wait two animation frames so the new page actually paints
      // before we uncover — without this the cover drops a frame
      // early and the user sees the old/wrong page.
      await new Promise<void>((r) =>
        requestAnimationFrame(() => requestAnimationFrame(() => r())),
      );
      if (stale()) return;
      hideCover();
      if (savedCfi) currentCfi = savedCfi;
      suppressCfiUpdates = false;
      await precomputeAllPages();
      if (stale()) return;
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const loc = (view as any)?.lastLocation;
      if (loc) {
        view!.dispatchEvent(new CustomEvent('relocate', { detail: loc }));
      }
    } catch {
      if (!stale()) {
        hideCover();
        suppressCfiUpdates = false;
      }
    }
  })();
}

// Force our bg color onto every element inside the foliate-view's
// shadow root. foliate uses mode:'open' so we can reach in, but new
// elements keep appearing (iframes, headers) so we also install a
// MutationObserver to cover anything added later.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function forceShadowBackground(host: any, bgColor: string): void {
  try {
    const sr: ShadowRoot | null = host.shadowRoot;
    if (!sr) return;
    let srStyle = sr.getElementById('readr-sr-theme') as HTMLStyleElement | null;
    if (!srStyle) {
      srStyle = document.createElement('style');
      srStyle.id = 'readr-sr-theme';
      sr.prepend(srStyle);
    }
    srStyle.textContent =
      `:host{background:${bgColor}!important}` +
      `*{background:${bgColor}!important;border:0!important;outline:0!important;box-shadow:none!important;column-rule:none!important}` +
      'iframe{border:none!important}';
    for (const el of sr.querySelectorAll('*')) {
      const s = (el as HTMLElement).style;
      s.setProperty('background', bgColor, 'important');
      s.setProperty('border', '0', 'important');
      s.setProperty('outline', '0', 'important');
      s.setProperty('box-shadow', 'none', 'important');
    }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const anySr = sr as any;
    if (!anySr._readrObserver) {
      anySr._readrObserver = new MutationObserver(() => {
        const bg = currentTheme?.bg || '#fff';
        for (const el of sr.querySelectorAll('*')) {
          (el as HTMLElement).style.setProperty('background', bg, 'important');
          (el as HTMLElement).style.setProperty('border-color', 'transparent', 'important');
        }
      });
      anySr._readrObserver.observe(sr, { childList: true, subtree: true });
    }
  } catch { /* ignore */ }
}

// ─── Page counting ────────────────────────────────────────────────────

function remeasureCurrentSection(): void {
  // Never overwrite locked (precomputed) values — they're authoritative.
  if (sectionPageCountsLocked) return;
  if (!currentSectionDoc || !view) return;
  const vw = view.clientWidth || window.innerWidth;
  if (vw <= 0) return;
  try {
    const sw = currentSectionDoc.documentElement.scrollWidth
      || currentSectionDoc.body?.scrollWidth || 0;
    if (sw > 0) {
      sectionPageCounts[currentSectionIndex] = Math.max(1, Math.ceil(sw / vw));
    }
  } catch { /* ignore */ }
}

// Measure page counts for ALL sections by loading each section's
// document via createDocument(), injecting theme CSS, and measuring
// scrollWidth in a hidden container. This gives exact page counts.
let _precomputeRunning = false;
async function precomputeAllPages(): Promise<void> {
  if (_precomputeRunning || !book?.sections || !view) return;
  _precomputeRunning = true;

  // document.fonts.ready resolves immediately if no pending font is
  // actually in use. Explicitly force-load the theme font first so
  // scrollWidth measurements use final glyph metrics, not fallback.
  const fs = currentTheme.fontSize || 16;
  const ff = currentTheme.fontFamily || 'serif';
  try {
    if (document.fonts?.load) {
      await document.fonts.load(`${fs}px "${ff}"`);
    }
    await document.fonts?.ready;
  } catch { /* ignore */ }

  const vw = view.clientWidth || window.innerWidth;
  const vh = view.clientHeight || window.innerHeight || 800;
  if (vw <= 0) { _precomputeRunning = false; return; }

  const total = book.sections.length;
  let measured = 0;

  for (let i = 0; i < total; i++) {
    if (sectionPageCounts[i]) { measured++; continue; }
    try {
      const section = book.sections[i];
      const doc = await section.createDocument();
      if (!doc || !doc.body) { sectionPageCounts[i] = 1; measured++; continue; }

      const el = document.createElement('div');
      el.style.cssText =
        'position:fixed;left:-99999px;top:0;'
        + `width:${vw}px;height:${vh}px;`
        + `column-width:${vw}px;column-fill:auto;`
        + 'overflow:hidden;visibility:hidden;';
      if (currentThemeCSS) {
        const style = document.createElement('style');
        style.textContent = currentThemeCSS;
        el.appendChild(style);
      }
      el.innerHTML += doc.body.innerHTML;
      document.body.appendChild(el);

      const sw = el.scrollWidth;
      // ceil matches foliate's expand(): pageCount = ceil(contentSize/size)
      sectionPageCounts[i] = Math.max(1, Math.ceil(sw / vw));
      measured++;

      document.body.removeChild(el);
    } catch (err) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      post('debug', { msg: `precompute section ${i} failed: ${(err as any)?.message || err}` });
      sectionPageCounts[i] = 1;
      measured++;
    }
  }

  _precomputeRunning = false;

  let totalPages = 0;
  for (let i = 0; i < total; i++) totalPages += sectionPageCounts[i] ?? 1;
  sectionPageCountsLocked = true;
  post('debug', { msg: `precompute done: ${measured}/${total} sections, ${totalPages} pages` });
  post('pagesComputed', { totalPages, measured, total });
}

// ─── Search ──────────────────────────────────────────────────────────

async function performSearch(query: string): Promise<void> {
  if (!book || !query || !book.search) return;
  try {
    const results: Array<{ cfi: string; excerpt: string; section: string }> = [];
    for await (const result of book.search(query)) {
      results.push({ cfi: result.cfi, excerpt: result.excerpt, section: result.label });
      if (results.length >= 100) break;
    }
    post('searchResults', { results, query });
  } catch (err) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    post('searchResults', { results: [], query, error: (err as any)?.message });
  }
}

// ─── File fetching (file:// needs XHR, not fetch) ────────────────────

function fetchFile(url: string): Promise<Blob> {
  // fetch() doesn't work with file:// on Android WebView.
  // XMLHttpRequest does when allowFileAccess is enabled.
  if (url.startsWith('file://')) {
    return new Promise<Blob>((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open('GET', url, true);
      xhr.responseType = 'blob';
      xhr.onload = () => (xhr.status === 200 || xhr.status === 0)
        ? resolve(xhr.response)
        : reject(new Error('XHR failed: ' + xhr.status));
      xhr.onerror = () => reject(new Error('XHR network error'));
      xhr.send();
    });
  }
  return fetch(url).then((r) => {
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.blob();
  });
}

// ─── TOC flattening ──────────────────────────────────────────────────

interface FlatTocItem { label: string; href: string; depth: number; }
function flattenToc(toc: FoliateTocItem[], depth = 0): FlatTocItem[] {
  const items: FlatTocItem[] = [];
  for (const item of toc) {
    items.push({ label: item.label, href: item.href, depth });
    if (item.subitems) items.push(...flattenToc(item.subitems, depth + 1));
  }
  return items;
}

// ─── Main init ───────────────────────────────────────────────────────

async function init(): Promise<void> {
  const config = window.__READR_CONFIG;
  if (!config?.bookUrl) {
    showError('Missing __READR_CONFIG.bookUrl');
    return;
  }

  try {
    // foliate-bundle.js exposes window.__foliate = { makeBook, Overlayer }.
    const foliate = window.__foliate;
    if (!foliate) throw new Error('foliate-bundle not loaded');
    const { makeBook, Overlayer } = foliate;

    const blob = await fetchFile(config.bookUrl);
    const file = new File([blob], 'book.epub', { type: blob.type || 'application/epub+zip' });

    book = await makeBook(file);
    const loading = document.getElementById('loading');
    if (loading) loading.style.display = 'none';

    const viewer = document.getElementById('viewer');
    if (!viewer) throw new Error('#viewer not found');
    view = document.createElement('foliate-view') as FoliateView;
    viewer.appendChild(view);

    view.setAttribute('flow', 'paginated');
    view.setAttribute('margin', '48px');

    await view.open(book);

    // Docs we've already wired up. Each new section gets its own iframe
    // document; track in a WeakSet so re-attachment is idempotent.
    const attachedDocs = new WeakSet<Document>();

    function attachTapHandlers(doc: Document | null): void {
      if (!doc || attachedDocs.has(doc)) return;
      attachedDocs.add(doc);
      // Clicks inside foliate's section iframes don't bubble to the
      // parent document — attach directly so page-turn works from the
      // content area.
      doc.addEventListener('click', handleTap);
      // Capture-phase swipe blocker. Foliate registers its own
      // touchmove handler on each section doc (non-capturing), so we
      // intercept on the same doc during the capture phase and stop
      // the event before foliate's listener runs when swipe is off.
      doc.addEventListener('touchmove', blockSwipe, { capture: true, passive: false });
      // Suppress native Android context menu so our custom RN menu shows.
      doc.addEventListener('contextmenu', (ev) => {
        ev.preventDefault();
        ev.stopPropagation();
        return false;
      });
      // Text selection — debounce selectionchange + pointerup.
      let selDebounce: ReturnType<typeof setTimeout> | null = null;
      function checkSelection() {
        const sel = doc!.getSelection?.();
        if (sel && sel.toString().trim() && sel.rangeCount > 0 && !sel.isCollapsed) {
          let cfi = '';
          let rect: { x: number; y: number; w: number; h: number } | null = null;
          try {
            const range = sel.getRangeAt(0);
            const contents = view?.renderer?.getContents?.() ?? [];
            const content = contents.find((c) => c.doc.contains(range.startContainer));
            if (content && view?.getCFI) cfi = view.getCFI(content.index, range) ?? '';
            // Translate the range rect into top-window coordinates by
            // walking up frameElement chains — foliate nests the doc
            // inside one (or more) iframes.
            const r = range.getBoundingClientRect();
            let ox = 0, oy = 0;
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            let win: any = doc!.defaultView;
            while (win && win !== window && win.frameElement) {
              const fr = win.frameElement.getBoundingClientRect();
              ox += fr.left;
              oy += fr.top;
              win = win.parent;
            }
            rect = { x: r.left + ox, y: r.top + oy, w: r.width, h: r.height };
          } catch { /* ignore */ }
          post('selectionChanged', { text: sel.toString(), cfi, rect });
        } else {
          post('selectionCleared', {});
        }
      }
      doc.addEventListener('selectionchange', () => {
        if (selDebounce) clearTimeout(selDebounce);
        selDebounce = setTimeout(checkSelection, 200);
      });
      doc.addEventListener('pointerup', () => {
        setTimeout(checkSelection, 80);
      });
    }

    // Attach tap handlers to every currently-rendered section doc.
    // Called from both 'load' and 'relocate' so we never miss a new
    // iframe, even if the 'load' event was missed due to listener
    // registration timing or foliate internals.
    function ensureAllDocsAttached(): void {
      try {
        const contents = view?.renderer?.getContents?.() ?? [];
        for (const c of contents) attachTapHandlers(c.doc);
      } catch { /* ignore */ }
    }

    // Swallow touchmove when the user has disabled swipe-to-turn.
    // stopImmediatePropagation prevents foliate's own non-capturing
    // listener from running; preventDefault stops the browser from
    // interpreting it as a native scroll gesture. When swipe IS
    // enabled this is a no-op, so foliate handles gestures normally.
    function blockSwipe(e: TouchEvent): void {
      if (swipeEnabled) return;
      // Allow a single-finger scroll inside an active text selection
      // so selection drag handles keep working.
      e.preventDefault();
      e.stopImmediatePropagation();
    }

    // Tap zones for page turns (honors the tapToTurn theme flag).
    function handleTap(e: MouseEvent): void {
      // If there's an active text selection, clear it on tap instead
      // of navigating. The next tap will navigate normally.
      try {
        const d = ((e.view as Window | null) || window).document ?? document;
        const sel = d.getSelection?.() ?? window.getSelection?.();
        if (sel && !sel.isCollapsed && sel.toString().trim()) {
          sel.removeAllRanges();
          post('selectionCleared', {});
          return;
        }
      } catch { /* ignore */ }

      // Use the parent window's innerWidth and screenX for zone
      // detection. screenX is screen-absolute so it's stable across
      // iframe boundaries; innerWidth is the visible viewport.
      const w = window.innerWidth || screen.width;
      const x = e.screenX ?? e.clientX;
      if (tapToTurn && view) {
        if (x < w * 0.2) { view.prev(); return; }
        if (x > w * 0.8) { view.next(); return; }
      }
      post('tapCenter', {});
    }
    view.addEventListener('click', handleTap as EventListener);
    document.addEventListener('click', handleTap as EventListener);
    // Capture-phase swipe blocker on the foliate-view host itself —
    // mirrors the per-doc listener for touches outside any iframe
    // (e.g. the paginator header/footer/margin zones).
    view.addEventListener('touchmove', blockSwipe as EventListener, {
      capture: true,
      passive: false,
    });

    // Relay location changes. Foliate's relocate detail has `index` and
    // `fraction`. We reconstruct section index and compute an absolute
    // currentPage from the precomputed counts.
    view.addEventListener('relocate', (e) => {
      // Re-attach on every relocate as a safety net — idempotent via
      // the WeakSet so this only does work for newly-rendered docs.
      ensureAllDocsAttached();
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const d = (e as CustomEvent).detail as any;
      // Mirror the latest CFI for theme-change restoration. Skip if
      // missing — never overwrite a known-good CFI with null. Also
      // skip while applyTheme is mid-transition: the reflow fires
      // intermediate relocate events with start-of-section CFIs that
      // would corrupt the saved value.
      if (!suppressCfiUpdates && typeof d.cfi === 'string' && d.cfi) {
        currentCfi = d.cfi;
      }
      const frac: number = d.fraction ?? 0;
      const totalSections = book?.sections?.length ?? 1;
      const secIdx = Math.max(0, Math.min(totalSections - 1, d.section?.current ?? 0));
      const sectionFractions = view?.getSectionFractions?.() ?? [];

      // Prefer foliate's own paginator counts for the current section —
      // they match exactly what it uses for navigation. Scrollwidth-
      // based precompute can drift ±1 from foliate's count, so we
      // overwrite the precomputed value with the authoritative one
      // whenever we actually render a section.
      let pagesInSection: number;
      let pageInSection: number;
      const rPages = view?.renderer?.pages;
      const rPage = view?.renderer?.page;
      if (typeof rPages === 'number' && rPages > 2 && typeof rPage === 'number') {
        pagesInSection = Math.max(1, rPages - 2);
        pageInSection = Math.max(1, Math.min(pagesInSection, rPage));
        sectionPageCounts[secIdx] = pagesInSection;
      } else {
        // Fallback — renderer not ready. Use scrollwidth if we've
        // never seen this section, then derive page from the fraction.
        const vw = (view?.clientWidth || window.innerWidth) ?? 0;
        if (!sectionPageCountsLocked && !sectionPageCounts[secIdx] && currentSectionDoc && vw > 0) {
          try {
            const sw = currentSectionDoc.documentElement.scrollWidth
              || currentSectionDoc.body?.scrollWidth || 0;
            if (sw > 0) sectionPageCounts[secIdx] = Math.max(1, Math.ceil(sw / vw));
          } catch { /* ignore */ }
        }
        pagesInSection = sectionPageCounts[secIdx] ?? 1;
        pageInSection = 1;
        if (pagesInSection > 1) {
          const sectionStart = sectionFractions[secIdx] ?? (secIdx / totalSections);
          const sectionEnd = sectionFractions[secIdx + 1] ?? ((secIdx + 1) / totalSections);
          const sectionSpan = Math.max(0, sectionEnd - sectionStart);
          const sectionFrac = sectionSpan > 0
            ? Math.min(1, Math.max(0, (frac - sectionStart) / sectionSpan))
            : 0;
          pageInSection = Math.max(1, Math.min(pagesInSection, Math.round(sectionFrac * pagesInSection) || 1));
        }
      }

      // Total pages — sum measured counts; for unmeasured ones we
      // estimate using the current section's page count (only used
      // briefly during initial load before precompute finishes).
      let totalPages = 0;
      let pagesBefore = 0;
      for (let i = 0; i < totalSections; i++) {
        const count = sectionPageCounts[i] ?? pagesInSection;
        if (i < secIdx) pagesBefore += count;
        totalPages += count;
      }
      totalPages = Math.max(1, totalPages);

      // Current page = sum of prior sections + page in current section.
      // Only way to keep currentPage consistent with pageInSection
      // across non-uniform section sizes.
      const currentPage = Math.max(1, Math.min(totalPages, pagesBefore + pageInSection));

      post('progressUpdated', {
        percentage: Math.round(frac * 1000) / 10,
        cfi: d.cfi,
        chapter: d.tocItem?.label,
        chapterHref: d.tocItem?.href,
        sectionIndex: secIdx,
        currentPage,
        totalPages,
        pageInSection,
        pagesInSection,
      });
    });

    // Annotation rendering — pick highlight vs note styling.
    view.addEventListener('draw-annotation', (e) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { draw, annotation } = (e as CustomEvent).detail ?? ({} as any);
      if (!draw || !annotation) return;
      if (annotation.kind === 'note') {
        // Typed notes get a wavy amber underline; drawings get a solid
        // indigo underline. On e-ink both collapse to crisp black
        // because the accent colours ghost out on slow panels.
        const eink = !!currentTheme?.isEink;
        if (annotation.noteType === 'handwritten') {
          draw((Overlayer as unknown as { underline: unknown }).underline, { color: eink ? '#000' : '#6366f1' });
        } else {
          draw((Overlayer as unknown as { squiggly: unknown }).squiggly, { color: eink ? '#000' : '#d97706' });
        }
      } else {
        const color = annotation.color || 'yellow';
        draw((Overlayer as unknown as { highlight: unknown }).highlight, { color });
      }
    });

    view.addEventListener('show-annotation', (e) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const ann = (e as CustomEvent).detail ?? ({} as any);
      // Foliate strips custom annotation fields before dispatch, so
      // fall back to the noteCfis map to tell a note apart from a
      // highlight by value alone.
      if (ann.value && noteCfis.has(ann.value)) {
        post('noteTapped', { cfi: ann.value, noteType: noteCfis.get(ann.value) });
      } else {
        post('showAnnotation', ann);
      }
    });

    // Foliate fires 'load' with { doc, index } for every newly-loaded
    // section. We keep a pointer to the current doc (TTS scrapes it),
    // inject theme CSS, trigger a remeasure, and wire up tap handlers.
    view.addEventListener('load', (e) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const detail = (e as CustomEvent).detail as any;
      if (detail?.doc) {
        currentSectionDoc = detail.doc as Document;
        injectThemeIntoDoc(currentSectionDoc);
        currentSectionIndex = detail.index;
        setTimeout(() => remeasureCurrentSection(), 200);
        attachTapHandlers(currentSectionDoc);
      }
    });

    view.addEventListener('external-link', (e) => {
      e.preventDefault();
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const detail = (e as CustomEvent).detail as any;
      post('externalLink', { href: detail.href });
    });

    // Navigate to the first section so content renders immediately.
    // Must happen AFTER 'load'/'relocate' listeners are registered or
    // we'd miss the initial section's events.
    try {
      await view.goTo(book.toc?.[0]?.href ?? book.sections?.[0]?.id ?? 0);
    } catch { /* ignore */ }
    ensureAllDocsAttached();

    // Ready — RN will respond with setTheme, and applyTheme() owns the
    // precompute lifecycle from there (font-ready gated).
    post('ready', {});

    if (book.toc) post('tocLoaded', { chapters: flattenToc(book.toc) });
  } catch (err) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    showError('Failed to load book: ' + ((err as any)?.message ?? String(err)));
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    post('error', { message: (err as any)?.message ?? String(err) });
  }
}

function showError(msg: string): void {
  const loading = document.getElementById('loading');
  if (loading) loading.style.display = 'none';
  const errorDiv = document.getElementById('error');
  if (errorDiv) {
    errorDiv.style.display = 'flex';
    errorDiv.textContent = msg;
  }
}

// Wire up incoming RN messages. postMessage from RN injects a
// MessageEvent with JSON.stringify'd payload in data.
window.addEventListener('message', (e: MessageEvent) => {
  try { handleRNMessage(JSON.parse(e.data)); } catch { /* ignore */ }
});
// eslint-disable-next-line @typescript-eslint/no-explicit-any
document.addEventListener('message' as any, (e: any) => {
  try { handleRNMessage(JSON.parse(e.data)); } catch { /* ignore */ }
});

init();
