/// <reference lib="dom" />
/// <reference lib="dom.iterable" />
/**
 * EPUB reader client — runs inside the Android WebView. Bundled by
 * esbuild into `assets/js/reader-bundle.js` and loaded via a
 * `<script src="file:///android_asset/js/reader-bundle.js">` tag from
 * the HTML generated by `components/reader/epub-html.ts`.
 *
 * Runtime inputs come from `window.__READR_CONFIG` (set by a tiny
 * inline script in the HTML before this bundle loads) and from
 * postMessage events sent by the RN host via `injectJavaScript` /
 * direct postMessage.
 */

// ─── Globals ──────────────────────────────────────────────────────────

declare global {
  interface Window {
    ReactNativeWebView?: { postMessage(data: string): void };
    __foliate?: {
      makeBook: (f: File) => Promise<FoliateBook>;
      Overlayer: FoliateOverlayer;
    };
    __READR_CONFIG?: { bookUrl: string };
  }
}

// Foliate-js has no public TS types; these are the shallow slices we
// rely on. `any` escape hatches are marked — they're where foliate's
// internal machinery is too gnarly to describe compactly.
interface FoliateTocItem {
  label: string;
  href: string;
  subitems?: FoliateTocItem[];
}
interface FoliateBook {
  sections: Array<{ id?: string; createDocument(): Promise<Document> }>;
  toc?: FoliateTocItem[];
  search?(q: string): AsyncIterable<{ cfi: string; excerpt: string; label: string }>;
}
interface FoliateOverlayer {
  highlight: unknown;
  underline: unknown;
  squiggly: unknown;
}
interface FoliateRenderer extends HTMLElement {
  page?: number;
  pages?: number;
  setStyles?(styles: string | [string, string]): void;
  getContents?(): Array<{ doc: Document; index: number }>;
}
interface FoliateView extends HTMLElement {
  open(book: FoliateBook): Promise<void>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  goTo(target: any): Promise<unknown>;
  goToFraction(f: number): Promise<unknown>;
  prev(): Promise<unknown>;
  next(): Promise<unknown>;
  clearSearch?(): void;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  addAnnotation?(ann: any, remove?: boolean): void;
  getCFI?(index: number, range: Range): string;
  getSectionFractions?(): number[];
  renderer?: FoliateRenderer;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  lastLocation?: any;
}

interface Theme {
  bg?: string;
  fg?: string;
  fontSize?: number;
  lineHeight?: number;
  fontWeight?: number;
  fontFamily?: string;
  margin?: number;
  marginV?: number;
  tapToTurn?: boolean;
  pageTurnMode?: 'tap' | 'swipe' | 'both';
  isEink?: boolean;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type RNMessage = { type: string; payload?: any };

// ─── Module state ─────────────────────────────────────────────────────

let view: FoliateView | null = null;
let book: FoliateBook | null = null;
// Kept so measurement can re-parse the book into a separate instance
// for a hidden measurement view without touching the main view's state.
let bookFile: File | null = null;
// Whether tap-on-left/right turns the page. Flipped from setTheme.
let tapToTurn = true;
// Whether swipe/drag gestures are allowed to turn pages. When false,
// capture-phase touch listeners on the paginator AND each iframe doc
// swallow touchmove so foliate's built-in swipe handler never fires.
let swipeEnabled = true;
// Most recently-loaded section document. Foliate loads each EPUB
// section into its own iframe; TTS and tap-handler installation
// operate on whatever's currently shown.
let currentSectionDoc: Document | null = null;

// Page counting — populated asynchronously by measurement running in a
// hidden second foliate-view. While unlocked, the relocate handler
// falls back to foliate's byte-based `location.total` as a stub.
let sectionPageCounts: Record<number, number> = {};
let sectionPageCountsLocked = false;

// Theme CSS that gets injected into every new section document.
let currentThemeCSS = '';
let currentTheme: Theme = {};
// Map of note CFI → noteType ('typed' | 'handwritten'). Foliate's
// show-annotation event drops custom annotation fields, so we mirror
// classifications here and consult it when routing a tap.
const noteCfis = new Map<string, 'typed' | 'handwritten'>();

// Monotonic timestamp of the most recent show-annotation event.
// Foliate fires show-annotation BEFORE the DOM click bubbles, so
// when handleTap runs we can check whether an annotation was just
// tapped and bail out instead of turning the page. 500ms is
// comfortably larger than the click-after-mousedown gap without
// interfering with a legitimate subsequent tap.
let lastAnnotationTapAt = 0;

// Full set of highlights we've added, keyed by cfi → color. Foliate
// discards its overlayer every time a section iframe is unloaded, so
// when the user navigates away and back we have to replay everything
// on the `create-overlay` event. Same for notes (stored in noteCfis).
const highlightRegistry = new Map<string, string>();

// ─── postMessage helpers ─────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function post(type: string, payload: any): void {
  window.ReactNativeWebView?.postMessage(JSON.stringify({ type, payload }));
}

// Compute progressUpdated payload from a foliate location detail and
// post it. Used by both the relocate listener and the post-measurement
// commit path so the math lives in exactly one place. Reads
// view.renderer state directly because that's the live source for
// per-section display values.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function computeAndPostProgress(d: any): void {
  if (!d || !view) return;
  const frac: number = d.fraction ?? 0;
  const totalSections = book?.sections?.length ?? 1;
  const secIdx = Math.max(0, Math.min(totalSections - 1, d.section?.current ?? 0));

  const rPages = view.renderer?.pages;
  const rPage = view.renderer?.page;
  const pagesInSection = typeof rPages === 'number' && rPages > 2 ? rPages - 2 : 1;
  const pageInSection = typeof rPage === 'number' && typeof rPages === 'number' && rPages > 2
    ? Math.max(1, Math.min(pagesInSection, rPage))
    : 1;

  let currentPage: number;
  let totalPages: number;
  let totalIsEstimate: boolean;

  if (sectionPageCountsLocked) {
    // Refine on visit: foliate's live paginator is the ultimate
    // source of truth for the section we're actually rendering. If
    // measurement drifted, update sectionPageCounts in place so the
    // mapping below is exact and total converges toward truth.
    if (typeof rPages === 'number' && rPages > 2) {
      const runtimeCount = rPages - 2;
      if (sectionPageCounts[secIdx] !== runtimeCount) {
        sectionPageCounts[secIdx] = runtimeCount;
      }
    }

    const sectionFractions = view.getSectionFractions?.() ?? [];
    const measuredPages = sectionPageCounts[secIdx] ?? 1;
    let pageInSectionMeasured = 1;
    if (measuredPages > 1) {
      const sectionStart = sectionFractions[secIdx] ?? (secIdx / totalSections);
      const sectionEnd = sectionFractions[secIdx + 1] ?? ((secIdx + 1) / totalSections);
      const sectionSpan = Math.max(0, sectionEnd - sectionStart);
      const sectionFrac = sectionSpan > 0
        ? Math.min(1, Math.max(0, (frac - sectionStart) / sectionSpan))
        : 0;
      pageInSectionMeasured = Math.max(
        1,
        Math.min(measuredPages, Math.round(sectionFrac * measuredPages) || 1),
      );
    }
    totalPages = 0;
    let pagesBefore = 0;
    for (let i = 0; i < totalSections; i++) {
      const count = sectionPageCounts[i] ?? 1;
      if (i < secIdx) pagesBefore += count;
      totalPages += count;
    }
    totalPages = Math.max(1, totalPages);
    currentPage = Math.max(1, Math.min(totalPages, pagesBefore + pageInSectionMeasured));
    totalIsEstimate = false;
  } else {
    // Stub: foliate's byte-based location.total. Note this is
    // invariant to font/margin (it's a byte-based estimate), so the
    // user won't see a number change until measurement locks.
    const loc = d.location;
    totalPages = loc?.total ?? 1;
    currentPage = loc?.current != null ? loc.current + 1 : 1;
    totalIsEstimate = true;
  }

  post('progressUpdated', {
    percentage: Math.round(frac * 1000) / 10,
    cfi: d.cfi,
    chapter: d.tocItem?.label,
    chapterHref: d.tocItem?.href,
    sectionIndex: secIdx,
    currentPage,
    totalPages,
    pageInSection,
    pagesInSection,
    totalIsEstimate,
  });
}

// ─── Incoming RN messages ─────────────────────────────────────────────

function handleRNMessage(data: RNMessage): void {
  if (!view) return;
  switch (data.type) {
    case 'setTheme':
      applyTheme(data.payload);
      break;
    case 'goToLocation': {
      // Await the nav so we can post 'restored' once foliate has
      // actually laid out the target page. RN uses that signal to
      // dismiss its loading overlay — avoids the first-section flash
      // that would otherwise show between init() and the resume nav.
      const v = view;
      (async (): Promise<void> => {
        try {
          if (data.payload.cfi) await v.goTo(data.payload.cfi);
          else if (data.payload.fraction != null)
            await v.goToFraction(data.payload.fraction);
        } catch { /* ignore */ }
        post('restored', {});
      })();
      break;
    }
    case 'goToChapter':
      if (data.payload.href) {
        try {
          view.goTo(data.payload.href);
        } catch {
          // Some hrefs need to be resolved against the book's base
          try { view.goTo({ href: data.payload.href }); } catch { /* ignore */ }
        }
      }
      break;
    case 'prevPage':
      view.prev();
      break;
    case 'nextPage':
      view.next();
      break;
    case 'search':
      performSearch(data.payload.query);
      break;
    case 'clearSearch':
      if (view.clearSearch) view.clearSearch();
      break;
    case 'getPageText': {
      // Return the visible section's plain text for TTS. Fall back to
      // empty string if the section hasn't loaded yet.
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const text = (currentSectionDoc?.body as any)?.innerText?.trim() ?? '';
      post('pageText', { text });
      break;
    }
    case 'copyToClipboard': {
      const text: string = data.payload.text || '';
      if (text) copyTextToClipboard(text);
      break;
    }
    case 'addHighlight': {
      const cfi = data.payload.cfi || data.payload.cfiRange;
      if (!cfi) break;
      const color = data.payload.color || 'yellow';
      highlightRegistry.set(cfi, color);
      if (view.addAnnotation) {
        try {
          view.addAnnotation({ value: cfi, color, kind: 'highlight' });
        } catch (err) {
          post('highlightError', { cfi, error: String(err) });
        }
      }
      break;
    }
    case 'removeHighlight': {
      const cfi = data.payload.cfi || data.payload.cfiRange;
      if (!cfi || !view.addAnnotation) break;
      highlightRegistry.delete(cfi);
      try {
        // foliate: passing truthy 2nd arg removes the annotation
        view.addAnnotation({ value: cfi }, true);
      } catch { /* ignore */ }
      break;
    }
    case 'addNote': {
      // Notes share foliate's annotation machinery but render as a
      // squiggly/underline so they're distinguishable from highlights
      // and don't block the underlying text. The noteType controls
      // the visual style so typed notes and drawings look different.
      const cfi: string | undefined = data.payload.cfi;
      const noteType: 'typed' | 'handwritten' =
        data.payload.noteType === 'handwritten' ? 'handwritten' : 'typed';
      if (!cfi || !view.addAnnotation) break;
      try {
        view.addAnnotation({ value: cfi, kind: 'note', noteType });
        noteCfis.set(cfi, noteType);
      } catch (err) {
        post('noteError', { cfi, error: String(err) });
      }
      break;
    }
    case 'removeNote': {
      const cfi: string | undefined = data.payload.cfi;
      if (!cfi || !view.addAnnotation) break;
      try {
        view.addAnnotation({ value: cfi }, true);
        noteCfis.delete(cfi);
      } catch { /* ignore */ }
      break;
    }
  }
}

function copyTextToClipboard(text: string): void {
  const fallback = () => {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.style.position = 'fixed';
    ta.style.left = '-9999px';
    document.body.appendChild(ta);
    ta.select();
    document.execCommand('copy');
    document.body.removeChild(ta);
  };
  try {
    navigator.clipboard.writeText(text).catch(fallback);
  } catch {
    fallback();
  }
}

// ─── Theming ──────────────────────────────────────────────────────────

const BUNDLED_FONTS = [
  'Literata', 'Lora', 'Merriweather', 'EB Garamond', 'Source Serif 4',
  'Noto Serif', 'Crimson Text', 'Libre Baskerville', 'Playfair Display',
  'PT Serif', 'Roboto Slab', 'Roboto', 'Open Sans', 'Inter', 'Nunito',
  'Fira Mono', 'IBM Plex Mono',
];

function fontFaceCSS(): string {
  return BUNDLED_FONTS.map((f) => {
    const file = f.replace(/\s+/g, '');
    return `@font-face{font-family:'${f}';src:url('file:///android_asset/fonts/${file}.ttf')}`;
  }).join('\n');
}

function buildThemeCSS(theme: Theme): string {
  const eink = !!theme.isEink;
  const fg = theme.fg || '#111';
  const fs = theme.fontSize || 16;
  const lh = theme.lineHeight || 1.6;
  const fw = theme.fontWeight || 400;
  const ff = theme.fontFamily || '';
  const marginH = theme.margin ?? 48;

  const base = [
    fontFaceCSS(),
    // Keep the iframe completely transparent so the host's theme bg
    // shows through — no inner/outer colour mismatch possible, even
    // while a mid-transition section is still carrying old styles.
    `html, body { background: transparent !important; }`,
    // Force ALL elements: color, transparent bg, typography, no borders.
    // Books embed their own stylesheets that add decorative borders in
    // hard-coded colours (sepia rules, beige dividers, etc) which stay
    // stale through theme changes. Kill them all — the theme's
    // typography should speak for itself.
    '* {',
    `  color: ${fg} !important;`,
    `  background: transparent !important;`,
    `  background-color: transparent !important;`,
    `  background-image: none !important;`,
    `  border: 0 !important;`,
    `  outline: 0 !important;`,
    `  box-shadow: none !important;`,
    `  line-height: ${lh} !important;`,
    `  font-weight: ${fw} !important;`,
    ff ? `  font-family: ${ff} !important;` : '',
    '}',
    // Tables still need their grid to be readable — restore a minimal
    // themed border for table cells only.
    `table, th, td { border: 1px solid ${fg} !important; border-collapse: collapse !important; }`,
    `html { font-size: ${fs}px !important; }`,
    // Horizontal page inset lives inside the section document. Vertical
    // top/bottom gutter comes from foliate's paginator `margin`
    // attribute, which is the renderer primitive intended for it.
    `body { margin: 0 !important; padding: 0 ${marginH}px !important; box-sizing: border-box !important; }`,
    'img { max-width: 100% !important; height: auto !important; background-color: transparent !important; }',
    'a, a:link, a:visited { text-decoration: underline; }',
  ];

  if (eink) {
    // Kill everything a slow panel can't handle. Books embed their own
    // stylesheets that can add fades, glows, and color decorations; the
    // !important wildcards win over them.
    base.push(
      'img { filter: grayscale(100%) contrast(1.15); }',
      '* {',
      '  text-shadow: none !important;',
      '  animation: none !important;',
      '  transition: none !important;',
      '  filter: none !important;',
      '}',
      // Re-apply after wildcard reset.
      'img { filter: grayscale(100%) contrast(1.15) !important; }',
      `a, a:link, a:visited, a:hover { color: ${fg} !important; text-decoration: underline; }`,
    );
  }

  return base.join('\n');
}

function injectThemeIntoDoc(doc: Document | null): void {
  if (!doc || !currentThemeCSS) return;
  try {
    let style = doc.getElementById('readr-theme') as HTMLStyleElement | null;
    if (!style) {
      style = doc.createElement('style');
      style.id = 'readr-theme';
      (doc.head || doc.documentElement).appendChild(style);
    }
    style.textContent = currentThemeCSS;
  } catch { /* ignore */ }
}

// Push the current theme CSS into every section iframe foliate has
// mounted. Foliate keeps adjacent sections alive for fast page turns,
// so injecting only into `currentSectionDoc` leaves the others stuck
// on the previous theme — visible as a flash of the old background
// when you turn a page after a theme change.
function injectThemeIntoAllDocs(): void {
  try {
    const contents = view?.renderer?.getContents?.() ?? [];
    for (const c of contents) injectThemeIntoDoc(c.doc);
  } catch { /* ignore */ }
  // Also cover currentSectionDoc in case getContents is empty (fresh
  // load, renderer not ready yet).
  if (currentSectionDoc) injectThemeIntoDoc(currentSectionDoc);
}

function applyThemeStyles(): void {
  if (!currentThemeCSS) return;
  try {
    // Foliate's renderer.setStyles() is the path that updates the
    // live paginator and calls expand() after the style change. Just
    // mutating a style tag inside the iframe can leave pagination
    // stale, which is why the margin controls looked dead.
    view?.renderer?.setStyles?.(currentThemeCSS);
  } catch { /* ignore */ }
  // Keep any already-mounted adjacent docs in sync as a fallback.
  injectThemeIntoAllDocs();
}

// Serialized signature of layout-affecting theme fields. We compare
// this against the previous call's signature to decide whether a
// given applyTheme needs to trigger a reflow or not.
function layoutSignature(t: Theme): string {
  return JSON.stringify([
    t.margin ?? null,
    t.marginV ?? null,
    t.fontSize ?? null,
    t.fontFamily ?? null,
    t.fontWeight ?? null,
    t.lineHeight ?? null,
  ]);
}
let lastLayoutSig: string | null = null;

function applyTheme(theme: Theme): void {
  const prevTheme = currentTheme;
  currentTheme = theme;
  const sig = layoutSignature(theme);
  // First call (lastLayoutSig null) ALWAYS runs the full path so
  // margins/gap/etc get initially applied. Subsequent calls only
  // reflow when the signature changed; colour-only changes skip.
  const isFirst = lastLayoutSig == null;
  const layoutChanged = isFirst || sig !== lastLayoutSig;
  lastLayoutSig = sig;
  post('debug', { msg: `applyTheme isFirst=${isFirst} layoutChanged=${layoutChanged} prevBg=${prevTheme.bg} newBg=${theme.bg}` });

  // ── Colour work (always, cheap, no reflow) ───────────────────────
  const root = document.documentElement;
  root.style.setProperty('--bg', theme.bg || '#fff');
  root.style.setProperty('--fg', theme.fg || '#111');
  const bgColor = theme.bg || '#fff';
  root.style.cssText = `background:${bgColor}!important`;
  document.body.style.cssText = `background:${bgColor}!important;margin:0;padding:0`;
  const viewer = document.getElementById('viewer');
  if (viewer) viewer.style.cssText = `width:100%;height:100%;background:${bgColor}`;
  if (view) {
    view.style.background = bgColor;
    forceShadowBackground(view, bgColor);
  }

  // Page-turn mode (not layout-affecting)
  const mode: 'tap' | 'swipe' | 'both' =
    theme.pageTurnMode ?? (theme.tapToTurn === false ? 'swipe' : 'both');
  tapToTurn = mode !== 'swipe';
  swipeEnabled = mode !== 'tap';

  // Keep the section-iframe CSS string current so new sections pick
  // up the latest theme. Also push it into the current section doc —
  // foliate's column positions stay put through an in-iframe restyle,
  // so the visible page doesn't jump on a colour-only change.
  currentThemeCSS = buildThemeCSS(theme);
  applyThemeStyles();

  const renderer = view?.renderer;
  if (!renderer) return;

  // ── Layout work (only when something layout-affecting changed) ───
  if (!layoutChanged) return;

  // Apply layout attributes to foliate's actual paginator, not the
  // outer foliate-view wrapper. The paginator keeps its own anchor
  // across render() calls, so we can let it reflow in place instead of
  // blanking the screen and manually restoring by CFI.
  // Foliate expects `gap` as a percentage, while the max-* caps and
  // margin use px lengths. Keep those units aligned with the paginator
  // contract or its grid math falls back to the defaults.
  renderer.setAttribute('flow', 'paginated');
  renderer.setAttribute('gap', '0%');
  renderer.setAttribute('max-inline-size', '99999px');
  renderer.setAttribute('max-block-size', '99999px');
  renderer.setAttribute('margin', `${theme.marginV ?? 24}px`);
  sectionPageCounts = {};
  sectionPageCountsLocked = false;
  _measureSeq++;
  post('debug', {
    msg: `applyTheme triggered remeasure seq=${_measureSeq} margin=${theme.margin} marginV=${theme.marginV} fs=${theme.fontSize} ff=${theme.fontFamily}`,
  });
  requestAnimationFrame(() => {
    void runMeasurement();
  });
}

// Force our bg color onto every element inside the foliate-view's
// shadow root. foliate uses mode:'open' so we can reach in, but new
// elements keep appearing (iframes, headers) so we also install a
// MutationObserver to cover anything added later.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function forceShadowBackground(host: any, bgColor: string): void {
  try {
    const sr: ShadowRoot | null = host.shadowRoot;
    if (!sr) return;
    let srStyle = sr.getElementById('readr-sr-theme') as HTMLStyleElement | null;
    if (!srStyle) {
      srStyle = document.createElement('style');
      srStyle.id = 'readr-sr-theme';
      sr.prepend(srStyle);
    }
    srStyle.textContent =
      `:host{background:${bgColor}!important}` +
      `*{background:${bgColor}!important;border:0!important;outline:0!important;box-shadow:none!important;column-rule:none!important}` +
      'iframe{border:none!important}';
    for (const el of sr.querySelectorAll('*')) {
      const s = (el as HTMLElement).style;
      s.setProperty('background', bgColor, 'important');
      s.setProperty('border', '0', 'important');
      s.setProperty('outline', '0', 'important');
      s.setProperty('box-shadow', 'none', 'important');
    }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const anySr = sr as any;
    if (!anySr._readrObserver) {
      anySr._readrObserver = new MutationObserver(() => {
        const bg = currentTheme?.bg || '#fff';
        for (const el of sr.querySelectorAll('*')) {
          (el as HTMLElement).style.setProperty('background', bg, 'important');
          (el as HTMLElement).style.setProperty('border-color', 'transparent', 'important');
        }
      });
      anySr._readrObserver.observe(sr, { childList: true, subtree: true });
    }
  } catch { /* ignore */ }
}

// ─── Page counting ────────────────────────────────────────────────────
//
// Page counts are measured asynchronously by a hidden second
// foliate-view that walks through every section. We use foliate's
// own renderer so the count for section N is guaranteed to match the
// main view's count when the user actually navigates there — same
// iframe, same columnize CSS, same fonts.ready gating.
//
// Re-measurement is kicked off whenever a layout-affecting theme
// field changes (font size, margin, font family, etc). A monotonic
// sequence number lets a newer request supersede an in-flight run:
// the running loop checks the seq after every section and bails
// early. After the loop, results are only committed if the seq
// still matches.

let _measureSeq = 0;
let _measureRunning = false;

async function runMeasurement(): Promise<void> {
  if (_measureRunning) return; // in-flight loop will pick up seq bumps
  _measureRunning = true;

  try {
    while (true) {
      const mySeq = _measureSeq;
      const ok = await measureOnce(mySeq);
      if (ok && mySeq === _measureSeq) break;
      // Either measurement was cancelled mid-run (seq bumped) or it
      // failed. If seq advanced, loop and run again. Otherwise bail.
      if (mySeq === _measureSeq) break;
    }
  } finally {
    _measureRunning = false;
  }
}

async function measureOnce(mySeq: number): Promise<boolean> {
  const foliate = window.__foliate;
  if (!foliate || !view || !bookFile) return false;

  const vw = view.clientWidth || window.innerWidth;
  const vh = view.clientHeight || window.innerHeight || 800;
  if (vw <= 0 || vh <= 0) return false;

  const host = document.createElement('div');
  host.id = 'readr-measure-host';
  host.style.cssText =
    'position:fixed;left:-99999px;top:0;'
    + `width:${vw}px;height:${vh}px;`
    + 'visibility:hidden;pointer-events:none;';
  document.body.appendChild(host);

  const t0 = Date.now();
  post('debug', {
    msg: `measure start seq=${mySeq} vw=${vw} vh=${vh} margin=${currentTheme.margin} marginV=${currentTheme.marginV} fs=${currentTheme.fontSize}`,
  });
  try {
    // Fresh book instance so the hidden view's section iframes never
    // collide with the main view's active section loader.
    const mbook = await foliate.makeBook(bookFile);
    if (mySeq !== _measureSeq) return false;
    if (!mbook.sections?.length) return true;

    const mview = document.createElement('foliate-view') as FoliateView;
    host.appendChild(mview);
    await mview.open(mbook);
    if (mySeq !== _measureSeq) return false;

    // Mirror the main view's paginator layout EXACTLY — any divergence
    // means our measured counts won't match what the main view renders.
    const r = mview.renderer;
    if (r) {
      r.setAttribute('flow', 'paginated');
      r.setAttribute('gap', '0%');
      r.setAttribute('max-inline-size', '99999px');
      r.setAttribute('max-block-size', '99999px');
      r.setAttribute('margin', `${currentTheme.marginV ?? 24}px`);
      if (currentThemeCSS) r.setStyles?.(currentThemeCSS);
    }

    // Make sure fonts are loaded before we start measuring. Foliate
    // also per-section awaits fonts.ready but covering it here means
    // the first section isn't measured against a fallback font.
    try { await document.fonts?.ready; } catch { /* ignore */ }

    const total = mbook.sections.length;
    const counts: number[] = new Array(total).fill(1);

    for (let i = 0; i < total; i++) {
      if (mySeq !== _measureSeq) return false;
      try {
        // foliate-view.goTo accepts a number as a section-index
        // shortcut. Passing `{ index, anchor }` falls through to the
        // href branch (it tries `.split()` on the object) and throws.
        await mview.goTo(i);
      } catch (err) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        post('debug', { msg: `measure goTo ${i} failed: ${(err as any)?.message || err}` });
        continue;
      }

      // Foliate's paginator awaits the iframe's own fonts.ready and
      // re-runs expand() when fonts arrive. We must wait for that or
      // we'll record a count taken with the fallback font's metrics —
      // which then disagrees with the main view's count and breaks
      // the proportional mapping in the relocate handler.
      try {
        const contents = mview.renderer?.getContents?.() ?? [];
        for (const c of contents) {
          if (c.doc?.fonts?.ready) await c.doc.fonts.ready;
        }
      } catch { /* ignore */ }

      // Poll .pages until it stops changing for two consecutive reads.
      // ResizeObserver-driven expand() reruns can land asynchronously
      // after image decode or late style application; this catches
      // them. Capped at ~150ms so a pathological section can't stall.
      let stable = mview.renderer?.pages ?? 0;
      for (let attempt = 0; attempt < 8; attempt++) {
        await new Promise<void>((r2) => setTimeout(r2, 16));
        const cur = mview.renderer?.pages ?? 0;
        if (cur > 0 && cur === stable) break;
        stable = cur;
      }
      counts[i] = stable > 2 ? stable - 2 : 1;

      // Yield to input handling between sections.
      await new Promise<void>((r2) => setTimeout(r2, 0));
    }

    if (mySeq !== _measureSeq) return false;

    // Commit: swap in the measured counts and lock.
    const next: Record<number, number> = {};
    let totalPages = 0;
    for (let i = 0; i < total; i++) {
      next[i] = counts[i];
      totalPages += counts[i];
    }
    sectionPageCounts = next;
    sectionPageCountsLocked = true;
    post('debug', {
      msg: `measure done seq=${mySeq}: ${total} sections, ${totalPages} pages in ${Date.now() - t0}ms`,
    });
    post('pagesComputed', { totalPages, measured: total, total });

    // Foliate doesn't auto-fire relocate when measurement completes,
    // so call computeAndPostProgress directly with the main view's
    // last location. This pushes the new total to RN immediately
    // without waiting for the user to flip a page.
    try {
      const last = view?.lastLocation;
      if (last) computeAndPostProgress(last);
    } catch { /* ignore */ }
    return true;
  } catch (err) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    post('debug', { msg: `measure failed: ${(err as any)?.message || err}` });
    return false;
  } finally {
    try { host.remove(); } catch { /* ignore */ }
  }
}

// ─── Search ──────────────────────────────────────────────────────────

async function performSearch(query: string): Promise<void> {
  if (!book || !query || !book.search) return;
  try {
    const results: Array<{ cfi: string; excerpt: string; section: string }> = [];
    for await (const result of book.search(query)) {
      results.push({ cfi: result.cfi, excerpt: result.excerpt, section: result.label });
      if (results.length >= 100) break;
    }
    post('searchResults', { results, query });
  } catch (err) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    post('searchResults', { results: [], query, error: (err as any)?.message });
  }
}

// ─── File fetching (file:// needs XHR, not fetch) ────────────────────

function fetchFile(url: string): Promise<Blob> {
  // fetch() doesn't work with file:// on Android WebView.
  // XMLHttpRequest does when allowFileAccess is enabled.
  if (url.startsWith('file://')) {
    return new Promise<Blob>((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open('GET', url, true);
      xhr.responseType = 'blob';
      xhr.onload = () => (xhr.status === 200 || xhr.status === 0)
        ? resolve(xhr.response)
        : reject(new Error('XHR failed: ' + xhr.status));
      xhr.onerror = () => reject(new Error('XHR network error'));
      xhr.send();
    });
  }
  return fetch(url).then((r) => {
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.blob();
  });
}

// ─── TOC flattening ──────────────────────────────────────────────────

interface FlatTocItem { label: string; href: string; depth: number; }
function flattenToc(toc: FoliateTocItem[], depth = 0): FlatTocItem[] {
  const items: FlatTocItem[] = [];
  for (const item of toc) {
    items.push({ label: item.label, href: item.href, depth });
    if (item.subitems) items.push(...flattenToc(item.subitems, depth + 1));
  }
  return items;
}

// ─── Main init ───────────────────────────────────────────────────────

async function init(): Promise<void> {
  const config = window.__READR_CONFIG;
  if (!config?.bookUrl) {
    showError('Missing __READR_CONFIG.bookUrl');
    return;
  }

  try {
    // foliate-bundle.js exposes window.__foliate = { makeBook, Overlayer }.
    const foliate = window.__foliate;
    if (!foliate) throw new Error('foliate-bundle not loaded');
    const { makeBook, Overlayer } = foliate;

    const blob = await fetchFile(config.bookUrl);
    const file = new File([blob], 'book.epub', { type: blob.type || 'application/epub+zip' });
    bookFile = file;

    book = await makeBook(file);
    const loading = document.getElementById('loading');
    if (loading) loading.style.display = 'none';

    const viewer = document.getElementById('viewer');
    if (!viewer) throw new Error('#viewer not found');
    view = document.createElement('foliate-view') as FoliateView;
    viewer.appendChild(view);
    await view.open(book);
    view.renderer?.setAttribute('flow', 'paginated');
    view.renderer?.setAttribute('gap', '0%');
    view.renderer?.setAttribute('max-inline-size', '99999px');
    view.renderer?.setAttribute('max-block-size', '99999px');
    view.renderer?.setAttribute('margin', `${currentTheme.marginV ?? 24}px`);

    // Docs we've already wired up. Each new section gets its own iframe
    // document; track in a WeakSet so re-attachment is idempotent.
    const attachedDocs = new WeakSet<Document>();

    function attachTapHandlers(doc: Document | null): void {
      if (!doc || attachedDocs.has(doc)) return;
      attachedDocs.add(doc);
      // Clicks inside foliate's section iframes don't bubble to the
      // parent document — attach directly so page-turn works from the
      // content area.
      doc.addEventListener('click', handleTap);
      // Capture-phase swipe blocker. Foliate registers its own
      // touchmove handler on each section doc (non-capturing), so we
      // intercept on the same doc during the capture phase and stop
      // the event before foliate's listener runs when swipe is off.
      doc.addEventListener('touchmove', blockSwipe, { capture: true, passive: false });
      // Suppress native Android context menu so our custom RN menu shows.
      doc.addEventListener('contextmenu', (ev) => {
        ev.preventDefault();
        ev.stopPropagation();
        return false;
      });
      // Text selection — debounce selectionchange + pointerup.
      let selDebounce: ReturnType<typeof setTimeout> | null = null;
      function checkSelection() {
        const sel = doc!.getSelection?.();
        if (sel && sel.toString().trim() && sel.rangeCount > 0 && !sel.isCollapsed) {
          let cfi = '';
          let rect: { x: number; y: number; w: number; h: number } | null = null;
          try {
            const range = sel.getRangeAt(0);
            const contents = view?.renderer?.getContents?.() ?? [];
            const content = contents.find((c) => c.doc.contains(range.startContainer));
            if (content && view?.getCFI) cfi = view.getCFI(content.index, range) ?? '';
            // Translate the range rect into top-window coordinates by
            // walking up frameElement chains — foliate nests the doc
            // inside one (or more) iframes.
            const r = range.getBoundingClientRect();
            let ox = 0, oy = 0;
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            let win: any = doc!.defaultView;
            while (win && win !== window && win.frameElement) {
              const fr = win.frameElement.getBoundingClientRect();
              ox += fr.left;
              oy += fr.top;
              win = win.parent;
            }
            rect = { x: r.left + ox, y: r.top + oy, w: r.width, h: r.height };
          } catch { /* ignore */ }
          post('selectionChanged', { text: sel.toString(), cfi, rect });
        } else {
          post('selectionCleared', {});
        }
      }
      doc.addEventListener('selectionchange', () => {
        if (selDebounce) clearTimeout(selDebounce);
        selDebounce = setTimeout(checkSelection, 200);
      });
      doc.addEventListener('pointerup', () => {
        setTimeout(checkSelection, 80);
      });
    }

    // Attach tap handlers to every currently-rendered section doc.
    // Called from both 'load' and 'relocate' so we never miss a new
    // iframe, even if the 'load' event was missed due to listener
    // registration timing or foliate internals.
    function ensureAllDocsAttached(): void {
      try {
        const contents = view?.renderer?.getContents?.() ?? [];
        for (const c of contents) attachTapHandlers(c.doc);
      } catch { /* ignore */ }
    }

    // Swallow touchmove when the user has disabled swipe-to-turn.
    // stopImmediatePropagation prevents foliate's own non-capturing
    // listener from running; preventDefault stops the browser from
    // interpreting it as a native scroll gesture. When swipe IS
    // enabled this is a no-op, so foliate handles gestures normally.
    function blockSwipe(e: TouchEvent): void {
      if (swipeEnabled) return;
      // Allow a single-finger scroll inside an active text selection
      // so selection drag handles keep working.
      e.preventDefault();
      e.stopImmediatePropagation();
    }

    // Tap zones for page turns (honors the tapToTurn theme flag).
    function handleTap(e: MouseEvent): void {
      // Annotation hit test. Foliate's Overlayer SVG has
      // pointer-events:none, so the click goes straight through to
      // the underlying text, and foliate does its own hitTest()
      // against stored rects to decide whether the click hit an
      // annotation. We do the SAME hitTest here before running
      // page-turn logic, so tapping a note marker opens the note
      // viewer WITHOUT also flipping pages or toggling the chrome.
      //
      // This is deterministic — no race on event ordering, no
      // timing hack. If the tap coordinates overlap an annotation
      // rect, we swallow the tap. If not, we proceed normally.
      try {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const contents = (view as any)?.renderer?.getContents?.() ?? [];
        for (const c of contents) {
          const overlayer = c?.overlayer;
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const hit = overlayer?.hitTest?.({ x: e.clientX, y: e.clientY });
          if (hit && hit[0]) {
            // Foliate's own click handler will dispatch
            // 'show-annotation' on the same event, which is what
            // opens the note viewer. We just have to NOT turn the
            // page.
            e.stopPropagation?.();
            return;
          }
        }
      } catch { /* ignore and fall through */ }

      // If there's an active text selection, clear it on tap instead
      // of navigating. The next tap will navigate normally. Done
      // synchronously because the selection may be wiped by foliate's
      // own bubble-phase listener if we wait.
      try {
        const d = ((e.view as Window | null) || window).document ?? document;
        const sel = d.getSelection?.() ?? window.getSelection?.();
        if (sel && !sel.isCollapsed && sel.toString().trim()) {
          sel.removeAllRanges();
          post('selectionCleared', {});
          return;
        }
      } catch { /* ignore */ }

      // Use the parent window's innerWidth and screenX for zone
      // detection. screenX is screen-absolute so it's stable across
      // iframe boundaries; innerWidth is the visible viewport.
      // Captured here so the deferred callback below stays valid even
      // after the event object is recycled.
      const w = window.innerWidth || screen.width;
      const x = e.screenX ?? e.clientX;

      // Defer the page-turn decision to the next macrotask so foliate's
      // own click listener — registered on the same iframe doc AFTER
      // ours via the lazy Lc(overlayer) setup — has finished its bubble
      // pass and dispatched 'show-annotation'. By the time this runs,
      // our show-annotation listener will have stamped
      // lastAnnotationTapAt for any note/highlight tap, so the recency
      // check below catches taps that the synchronous hit test above
      // missed (which it does for notes, since their hit rects are
      // just the underline strip rather than the full text span).
      setTimeout(() => {
        if (Date.now() - lastAnnotationTapAt < 500) return;
        if (tapToTurn && view) {
          if (x < w * 0.2) { view.prev(); return; }
          if (x > w * 0.8) { view.next(); return; }
        }
        post('tapCenter', {});
      }, 0);
    }
    view.addEventListener('click', handleTap as EventListener);
    document.addEventListener('click', handleTap as EventListener);
    // Capture-phase swipe blocker on the foliate-view host itself —
    // mirrors the per-doc listener for touches outside any iframe
    // (e.g. the paginator header/footer/margin zones).
    view.addEventListener('touchmove', blockSwipe as EventListener, {
      capture: true,
      passive: false,
    });

    // Relay location changes. The actual computation lives in
    // computeAndPostProgress() so the post-measurement commit path
    // can call exactly the same logic.
    view.addEventListener('relocate', (e) => {
      ensureAllDocsAttached();
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      computeAndPostProgress((e as CustomEvent).detail as any);
    });

    // Annotation rendering — pick highlight vs note styling.
    view.addEventListener('draw-annotation', (e) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { draw, annotation } = (e as CustomEvent).detail ?? ({} as any);
      if (!draw || !annotation) return;
      if (annotation.kind === 'note') {
        // Typed notes get a wavy amber underline; drawings get a solid
        // indigo underline. On e-ink both collapse to crisp black
        // because the accent colours ghost out on slow panels.
        const eink = !!currentTheme?.isEink;
        if (annotation.noteType === 'handwritten') {
          draw((Overlayer as unknown as { underline: unknown }).underline, { color: eink ? '#000' : '#6366f1' });
        } else {
          draw((Overlayer as unknown as { squiggly: unknown }).squiggly, { color: eink ? '#000' : '#d97706' });
        }
      } else {
        const color = annotation.color || 'yellow';
        draw((Overlayer as unknown as { highlight: unknown }).highlight, { color });
      }
    });

    view.addEventListener('show-annotation', (e) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const ann = (e as CustomEvent).detail ?? ({} as any);

      // Translate the annotation range's bounding rect into top-window
      // coordinates by walking up the iframe chain — the range lives
      // inside a section iframe, so its rect is relative to that doc.
      let rect: { x: number; y: number; w: number; h: number } | null = null;
      try {
        const range: Range | undefined = ann.range;
        if (range) {
          const r = range.getBoundingClientRect();
          const doc = range.startContainer?.ownerDocument ?? null;
          let ox = 0, oy = 0;
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          let win: any = doc?.defaultView;
          while (win && win !== window && win.frameElement) {
            const fr = win.frameElement.getBoundingClientRect();
            ox += fr.left;
            oy += fr.top;
            win = win.parent;
          }
          rect = { x: r.left + ox, y: r.top + oy, w: r.width, h: r.height };
        }
      } catch { /* ignore */ }

      // Mark the tap time so the page-turn tap handler (which runs
      // a few ms later when the click event bubbles) knows to skip
      // navigation — otherwise tapping a note marker both opens the
      // note viewer and flips the page.
      lastAnnotationTapAt = Date.now();

      // Foliate strips custom annotation fields before dispatch, so
      // fall back to the noteCfis map to tell a note apart from a
      // highlight by value alone.
      if (ann.value && noteCfis.has(ann.value)) {
        post('noteTapped', { cfi: ann.value, noteType: noteCfis.get(ann.value), rect });
      } else {
        post('showAnnotation', { value: ann.value, index: ann.index, rect });
      }
    });

    // Foliate destroys the overlayer every time a section iframe is
    // unloaded and creates a fresh empty one on return. It auto-replays
    // search results but not user annotations — we have to redraw
    // highlights + notes ourselves, otherwise they vanish when the
    // user leaves the page and comes back. addAnnotation() resolves
    // the cfi to a section index internally and only draws if it
    // matches the newly-created overlay, so firing every registered
    // annotation here is cheap and always correct.
    view.addEventListener('create-overlay', () => {
      if (!view?.addAnnotation) return;
      for (const [cfi, color] of highlightRegistry) {
        try {
          view.addAnnotation({ value: cfi, color, kind: 'highlight' });
        } catch { /* ignore */ }
      }
      for (const [cfi, noteType] of noteCfis) {
        try {
          view.addAnnotation({ value: cfi, kind: 'note', noteType });
        } catch { /* ignore */ }
      }
    });

    // Foliate fires 'load' with { doc, index } for every newly-loaded
    // section. We keep a pointer to the current doc (TTS scrapes it),
    // inject theme CSS, and wire up tap handlers.
    view.addEventListener('load', (e) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const detail = (e as CustomEvent).detail as any;
      if (detail?.doc) {
        currentSectionDoc = detail.doc as Document;
        injectThemeIntoDoc(currentSectionDoc);
        attachTapHandlers(currentSectionDoc);
      }
    });

    view.addEventListener('external-link', (e) => {
      e.preventDefault();
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const detail = (e as CustomEvent).detail as any;
      post('externalLink', { href: detail.href });
    });

    // Navigate to the first section so content renders immediately.
    // Must happen AFTER 'load'/'relocate' listeners are registered or
    // we'd miss the initial section's events.
    try {
      await view.goTo(book.toc?.[0]?.href ?? book.sections?.[0]?.id ?? 0);
    } catch { /* ignore */ }
    ensureAllDocsAttached();

    // Ready — RN will respond with setTheme, and applyTheme() owns the
    // precompute lifecycle from there (font-ready gated).
    post('ready', {});

    if (book.toc) post('tocLoaded', { chapters: flattenToc(book.toc) });
  } catch (err) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    showError('Failed to load book: ' + ((err as any)?.message ?? String(err)));
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    post('error', { message: (err as any)?.message ?? String(err) });
  }
}

function showError(msg: string): void {
  const loading = document.getElementById('loading');
  if (loading) loading.style.display = 'none';
  const errorDiv = document.getElementById('error');
  if (errorDiv) {
    errorDiv.style.display = 'flex';
    errorDiv.textContent = msg;
  }
}

// Wire up incoming RN messages. postMessage from RN injects a
// MessageEvent with JSON.stringify'd payload in data.
window.addEventListener('message', (e: MessageEvent) => {
  try { handleRNMessage(JSON.parse(e.data)); } catch { /* ignore */ }
});
// eslint-disable-next-line @typescript-eslint/no-explicit-any
document.addEventListener('message' as any, (e: any) => {
  try { handleRNMessage(JSON.parse(e.data)); } catch { /* ignore */ }
});

init();
